name: Selenium TestNG CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Updated to v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Run TestNG Tests
        run: mvn test -Dsurefire.printSummary=true --fail-at-end  # ✅ Ensures test results appear in logs

      - name: Debug: List Files in Target Directory
        run: ls -R target/ || echo "Target directory not found"

      - name: Debug: List Files in Surefire Reports Directory
        run: ls -R target/surefire-reports/ || echo "Surefire reports directory not found"

      - name: Upload Test Results
        if: success()
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: test-results
          path: target/surefire-reports/