name: Selenium TestNG CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Clean and Build with Maven
        run: mvn clean install --batch-mode --fail-at-end

      - name: Run TestNG Tests with Debugging
        run: mvn clean test -Dsurefire.failIfNoSpecifiedTests=false -Dsurefire.printSummary=true --fail-at-end

      - name: Debug - List Target Directory
        run: ls -R target/ || echo "❌ Target directory not found"

      - name: Debug - List Surefire Reports
        run: ls -R target/surefire-reports/ || echo "❌ Surefire reports directory not found"

      - name: Upload Test Results (If Exists)
        if: always()  # Runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
          if-no-files-found: warn  # Prevents failure if no test results exist
